### ISSUE TITLE
adding a fabform contact form 

### ISSUE THREAD

**Issue by derrygeoff** [razonyang/hugo-theme-bootstrap-skeleton#2]
Hello

Is there anyway you can add a https://fabform.io contact form to your theme?

Geoff
https://fabform.io

**Comment by razonyang** [comment]
It can be achieved via following parameter: 

```toml
[contact]
  endpoint = "YOUR_ENDPOINT"
```
