### ISSUE TITLE
[Question] Featured image is not showing

### ISSUE THREAD

**Issue by jaehyeon-kim** [razonyang/hugo-theme-bootstrap-skeleton#26]
Hello,

I see featured images are not showing except for the first post. I tried after clearing up browser cache and even in a new laptop but it is the same.

![image](https://user-images.githubusercontent.com/1023748/228940272-6e67a43c-ff81-41ac-a6dd-c41df2907adf.png)

When I click the image, however, it appears as shown below.

![image](https://user-images.githubusercontent.com/1023748/228941545-d55f72e9-5f2f-405a-826d-68f29e207921.png)

I work on docker and the docker compose file is shown below.

```
version: "3.5"

services:
  hugo:
      image: klakegg/hugo:0.107.0-ext-ubuntu
      command: server -D -F -E --poll 700ms --disableFastRender --ignoreCache --noHTTPCache --gc --forceSyncStatic
      container_name: hugo
      volumes:
        - $PWD:/src
        - /etc/ssl/certs:/etc/ssl/certs
      ports:
        - "1313:1313"
```

Can you please inform me how to fix it?

Cheers,
Jaehyeon
